import Head from "next/head";

import { Inter } from "next/font/google";

import mongoose from "mongoose";

import SearchTopper from "@/user/search-toppers";
import topper from "@/models/topper";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ Toppers }) {
  console.log(Toppers);
  return (
    <>
      <Head>
        <title>IAS Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <SearchTopper Toppers={Toppers}></SearchTopper>
      </div>
    </>
  );
}
export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI);
  }

  let Toppers = await topper.find();

  const slugs = Toppers.map((data) => {
    const slug = `${data.name.replace(/\s/g, "-")}-rank-${data.rank}-${
      data.year
    }`;
    return { ...data, slug };
  });

  return {
    props: { Toppers: JSON.parse(JSON.stringify(slugs)) },
  };
}
